[project]
name = "albert-hypr-window-switcher"
version = "2.1"
description = "Switch to your open windows on Hyprland swiftly"
readme = "README.md"
license = "LICENSE"
requires-python = ">=3.13"
dependencies = []
